name: Quality Gate Tests

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  quality-gate:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: obsidian-multi-git-plugin/package-lock.json
    
    - name: Install dependencies
      working-directory: obsidian-multi-git-plugin
      run: npm ci
    
    - name: Build TypeScript
      working-directory: obsidian-multi-git-plugin
      run: npm run build
    
    - name: Run Browser API Detection Tests
      working-directory: obsidian-multi-git-plugin
      run: npm run test:browser-api
    
    - name: Run Commit Flow Tests
      working-directory: obsidian-multi-git-plugin
      run: npm run test:commit-flow
    
    - name: Run All Tests with Coverage
      working-directory: obsidian-multi-git-plugin
      run: npm run test:coverage
    
    - name: Check Coverage Threshold
      working-directory: obsidian-multi-git-plugin
      run: |
        # 今後カバレッジ80%以上を必須とする
        echo "Coverage check passed - implement threshold in future"
    
    - name: Lint Check (if available)
      working-directory: obsidian-multi-git-plugin
      run: |
        if npm run lint --dry-run 2>/dev/null; then
          npm run lint
        else
          echo "No lint script found - skipping"
        fi
      continue-on-error: true