name: Test Obsidian Plugin

on:
  push:
    branches: [ master, main, develop ]
  pull_request:
    branches: [ master, main ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: obsidian-multi-git-plugin/package-lock.json
    
    - name: Install dependencies
      run: |
        cd obsidian-multi-git-plugin
        npm ci
    
    - name: Build plugin
      run: |
        cd obsidian-multi-git-plugin
        npm run build
    
    - name: Run unit tests
      run: |
        cd obsidian-multi-git-plugin
        npm run test:unit
    
    - name: Run integration tests
      run: |
        cd obsidian-multi-git-plugin
        npm run test:integration
    
    - name: Generate coverage report
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
      run: |
        cd obsidian-multi-git-plugin
        npm run test:coverage
    
    - name: Upload coverage to Codecov
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
      uses: codecov/codecov-action@v3
      with:
        directory: ./obsidian-multi-git-plugin/coverage
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.x'
        cache: 'npm'
        cache-dependency-path: obsidian-multi-git-plugin/package-lock.json
    
    - name: Install dependencies
      run: |
        cd obsidian-multi-git-plugin
        npm ci
    
    - name: Check TypeScript
      run: |
        cd obsidian-multi-git-plugin
        npx tsc --noEmit
    
    - name: Verify build
      run: |
        cd obsidian-multi-git-plugin
        npm run build
        test -f main.js